# Generated by Django 4.2.5 on 2023-09-29 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('debut_year', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song', models.CharField(max_length=255)),
                ('album_no', models.SmallIntegerField()),
                ('song_length', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_crud.album')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_crud.singer')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_crud.singer'),
        ),
    ]
